# -*- coding: utf-8 -*-
"""populations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adamlamee/CODINGinK12/blob/master/notebooks/populations.ipynb

# Populations of Predators and Prey

This activity will guide you in creating a double line graph using data below for Everglades Burmese Python and White-tailed Deer Populations.  

To get started,
- You won't hurt anything by experimenting. If you break it, close the tab and open the activity again to start over.
- Is this your first time? Need a refresher? Try the 5-minute [Intro to Coding activity](https://colab.research.google.com/github/adamlamee/CODINGinK12/blob/master/notebooks/intro.ipynb) and come back here.

When you're ready, run each code box until you get down to **Part One**.
"""

# Commented out IPython magic to ensure Python compatibility.
# We first have to import the software we'll need, called 'modules'
import numpy as np
import pandas as pd
# %matplotlib inline
import matplotlib.pyplot as plt

# We now need to read the data of Python and Deer populations over a number of years.
# Let's use the method ".read_csv" located in the "pd" module.

data = pd.read_csv("https://github.com/adamlamee/CODINGinK12/raw/master/data/populations.csv")

# This diplays the variable 'data'. It's the whole data table.
data

"""# Part One  
Look at the table of data above.  
- How many years of data are shown?  
- How many deer were present in the first year of the study?  
- When did the python population outnumber the deer?  
  
When you're ready, scroll down to **Part Two**.
"""

plt.plot(data['Year'], data['Pythons'], label='pythons', color='red', marker='o')
plt.plot(data['Year'], data['Deer'], label='deer', color='blue', marker='+')
plt.title('I could use a better title')
plt.xlabel('label me!')
plt.ylabel('label me, too!')
plt.xlim(2000,2015)
plt.ylim(100,1000)
plt.legend()
plt.show()

"""# Part Two  
The graph above shows how the animal populations in the Everglades changed.  
- The title and axis labels on the graph could use some work. Try editing the code above the graph, then run the code again to see the changes.  
- It's a good practice to have the y-axis begin at zero. Try fixing that.
- Also, the x-axis is too wide. Edit the code above to make the x-axis fot the years covered by the data.  
- If the study continued, what might happen to the deer population? Why is that?  
- Describe the shape of the python population's line. What happens near the end? Why do you think that?  
  
---  
## Saving Your Work  
This is running on a Google server on a distant planet and deletes what you've done when you close this tab. To save your work for later use or analysis you have a few options:  
- File > "Save a copy in Drive" will save it to you Google Drive in a folder called "Collaboratory". You can run it later from there.  
- File > "Download .ipynb" to save to your computer (and run with Jupyter software later)  
- File > Print to ... um ... print.  
- To save an image of a graph or chart, right-click on it and select Save Image as ...  

## Credits
The data came from the [Florida Fish and Wildlife Conservation Commission](https://myfwc.com/). UCF undergraduate Hunter T., who started the development of this notebook, was funded by Orange County Schools to make scientific computing a standard part of every middle school science class. This notebook was designed by [Adam LaMee](https://adamlamee.github.io/), who coordinated its development as the [PhysTEC](https://www.phystec.org/) Teacher-in-residence in the [University of Central Florida's Physics department](https://sciences.ucf.edu/physics/). Thanks to the great folks at [Binder](https://mybinder.org/) and [Google Colaboratory](https://colab.research.google.com/notebooks/intro.ipynb) for making this notebook interactive without you needing to download it or install [Jupyter](https://jupyter.org/) on your own device. Find more activities and license info at [CODINGinK12.org](http://www.codingink12.org).
"""